---
title: "Final Course Project Group Evaluations"
author: "Jesigga Sigurdardottir"
date: "2023-12-09"
output: pdf_document
---
<!--Directions
Use this RMD template to complete peer and self evaluations for your final project. Be sure to answer all prompts for each team member and yourself. You'll upload the knitted PDF (not the RMD) to the appropriate Canvas Portal.
--->


# Team Member 1

## Who are you evaluating?

*Full name of team member you are evaluating, or say "self-evaluation"*
Self Evaluation

## Evaluation Areas

#### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): __10_

Justification/Examples:

I researched my own data set, created the research questions, and created all the visualizations.


#### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): _10__

Justification/Examples:

I was very excited to work on this project.


#### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): _10__

Justification/Examples:


I communicated with myself to find time to finish this project in a timely manor.

#### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): _10__

Justification/Examples:


I have just turned in the project two days before the due date and have finished in a timely manor.


#### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): _10__

Justification/Examples:


I have worked by myself and completed the project.


### Total Score (out of 50): 50
